name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile
          yarn build

      - name: Pack
        run: |
          tar -c -f package.tar .next/standalone

      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          echo -e "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          scp -o StrictHostKeyChecking=no -v -P "49498" -r package.tar ghintegration@ovz1.kaa.0n03n.vps.myjino.ru:~

      - name: Unpack
        run: |
          ssh ghintegration@ovz1.kaa.0n03n.vps.myjino.ru 'tar -x -f package.tar'

